// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aoc2019;

namespace aoc2019.Migrations
{
    [DbContext(typeof(SpaceContext))]
    [Migration("20191212101016_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("aoc2019.SpaceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionZ1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionZ2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionZ3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionZ4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityX1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityX2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityX3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityX4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityY1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityY2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityY3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityY4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityZ1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityZ2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityZ3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VelocityZ4")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PositionX1", "PositionX2", "PositionX3", "PositionX4", "PositionY1", "PositionY2", "PositionY3", "PositionY4", "PositionZ1", "PositionZ2", "PositionZ3", "PositionZ4", "VelocityX1", "VelocityX2", "VelocityX3", "VelocityX4", "VelocityY1", "VelocityY2", "VelocityY3", "VelocityY4", "VelocityZ1", "VelocityZ2", "VelocityZ3", "VelocityZ4")
                        .IsUnique();

                    b.ToTable("SpaceState");
                });
#pragma warning restore 612, 618
        }
    }
}
